name: rick_and_morty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  injectable: ^2.4.4
  injectable_generator: ^2.6.2
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  dio: ^5.8.0+1
  get_it: ^8.0.3
  go_router: ^15.1.2
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  drift_dev: ^2.26.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11


flutter:
  uses-material-design: true
